maintainer       "xforty technologies"
maintainer_email "dking@xforty.com"
license          "Apache 2.0"
description      "Installs/Configures common xforty components"
long_description IO.read(File.join(File.dirname(__FILE__), 'README.rdoc'))
version          "0.0.1"
depends          "apt"
depends          "vim"
depends          "rpmforge"
depends          "selinux"
